// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdrcgpqgjwovrxijasjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcmNncHFnandvdnJ4aWphc2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODUzNDEsImV4cCI6MjA2Njc2MTM0MX0.pgD-3R3z51V3TBUqAC_dfEiLgijAllNECABwG4ayqPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);